// =====================================================================
// ae_tb.v
//
// ModelSim / iSim / Icarus testbench for ae_top. Drives 20 test vectors
// generated by quantize_ae.py (10 benign + 10 attack from CICIoT2023
// target domain) and verifies bit-accurate match against the Python
// INT16 reference (tb_expected.mem).
//
// IMPORTANT: this testbench expects to be run with the FPGA_Implementation
// directory layout intact:
//   sim/    -> ae_tb.v, tb_inputs.mem, tb_expected.mem
//   rtl/    -> ae_top.v + sub-modules
//   memory_init/ -> weights_L*.mem, biases_L*.mem, requant_L*.mem
//
// The simulator must run with its working directory at sim/ so that
// the relative paths "../memory_init/..." resolve. ae_top's $readmemh
// calls use bare basenames; we pass --include-dir or copy via the run
// script. Simplest: copy/symlink the memory_init files into sim/, OR
// run the simulator with `+incdir+../memory_init/`. The provided
// run_modelsim.do and run_icarus.sh handle this automatically.
//
// PASS criterion: anomaly_flag and mse_sum from HW match Python exactly.
// =====================================================================
`timescale 1ns / 1ps

module ae_tb;

    localparam integer ACT_W  = 16;
    localparam integer N_FEAT = 25;
    localparam integer N_VEC  = 20;
    localparam [31:0]  TAU_INT = 32'd3784122;

    // ---- Clock / reset ----
    reg clk = 1'b0;
    reg rst_n = 1'b0;
    always #10 clk = ~clk;   // 50 MHz (20 ns period)

    // ---- DUT signals ----
    reg                                start;
    reg  signed [N_FEAT*ACT_W-1:0]     x_flat;
    wire                               done;
    wire                               anomaly_flag;
    wire [32:0]                        mse_sum_out;

    ae_top #(
        .ACT_W   (ACT_W),
        .N_FEAT  (N_FEAT),
        .TAU_INT (TAU_INT)
    ) dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .start        (start),
        .x_flat       (x_flat),
        .done         (done),
        .anomaly_flag (anomaly_flag),
        .mse_sum_out  (mse_sum_out)
    );

    // ---- Test-vector memories ----
    reg [ACT_W-1:0] tb_in_mem [0:N_VEC*N_FEAT-1];
    integer tb_exp_anom    [0:N_VEC-1];
    integer tb_exp_mse     [0:N_VEC-1];
    integer tb_exp_label   [0:N_VEC-1];

    integer fh, sc, r;
    integer i, j;
    integer pass_count, fail_count;
    reg [255:0] line;
    reg [N_FEAT*ACT_W-1:0] vec_packed;

    initial begin
        start       = 1'b0;
        x_flat      = {(N_FEAT*ACT_W){1'b0}};
        pass_count  = 0;
        fail_count  = 0;

        $readmemh("tb_inputs.mem", tb_in_mem);

        fh = $fopen("tb_expected.mem", "r");
        if (fh == 0) begin
            $display("ERROR: cannot open tb_expected.mem");
            $finish;
        end
        // Skip header comment line
        r = $fgets(line, fh);
        for (i = 0; i < N_VEC; i = i + 1) begin
            sc = $fscanf(fh, "%d %d %d\n", tb_exp_anom[i], tb_exp_mse[i], tb_exp_label[i]);
        end
        $fclose(fh);

        // ---- Reset ----
        #50 rst_n = 1'b1;
        #20;

        // ---- Drive every test vector ----
        for (i = 0; i < N_VEC; i = i + 1) begin
            for (j = 0; j < N_FEAT; j = j + 1) begin
                vec_packed[j*ACT_W +: ACT_W] = tb_in_mem[i*N_FEAT + j];
            end
            x_flat <= vec_packed;
            @(posedge clk);
            start <= 1'b1;
            @(posedge clk);
            start <= 1'b0;

            wait (done == 1'b1);

            if ((anomaly_flag === tb_exp_anom[i][0]) && (mse_sum_out === tb_exp_mse[i])) begin
                $display("[PASS] vec %0d label=%0d: anom=%0d mse=%0d  (Python match)",
                         i, tb_exp_label[i], anomaly_flag, mse_sum_out);
                pass_count = pass_count + 1;
            end else begin
                $display("[FAIL] vec %0d label=%0d: HW(anom=%0d mse=%0d)  Expected(anom=%0d mse=%0d)",
                         i, tb_exp_label[i], anomaly_flag, mse_sum_out, tb_exp_anom[i], tb_exp_mse[i]);
                fail_count = fail_count + 1;
            end

            @(posedge clk);
        end

        $display("======================================================");
        $display("Bit-accurate verification: %0d/%0d vectors matched Python ref",
                 pass_count, N_VEC);
        $display("OVERALL: %s%s", (fail_count == 0) ? "PASS" : "FAIL",
                                   (fail_count == 0) ? "" : " (mismatches present)");
        $display("======================================================");
        $finish;
    end

    initial begin
        $dumpfile("ae_tb.vcd");
        $dumpvars(0, ae_tb);
    end

endmodule
